development:
  rpc_host: localhost
  rpc_port: 8101
  rpc_whitelist: "*"
  minerthreads: 1
  genesis_block: config/genesis.json
  datadir: /tmp/embark
  mine_when_needed: true
  gas_limit: 500000
  gas_price: 10000000000000
  console: false
  account:
    init: true
    password: config/password